// Spanish (Español) for the staff screens. Keys are the English text exactly as written in the app.
export const es: Record<string, string> = {
  "A colleague is covering your shift": "Un compañero cubre tu turno",
  "A notification 30 minutes before each shift.": "Un aviso 30 minutos antes de cada turno.",
  "Account": "Cuenta",
  "Add a note…": "Añade una nota…",
  "Add a service": "Añadir un servicio",
  "Add service": "Añadir servicio",
  "Add update": "Añadir actualización",
  "Admin": "Administrador",
  "All clear": "Todo en orden",
  "Allow camera": "Permitir cámara",
  "Amount": "Importe",
  "Anything the next shift should know?": "¿Algo que deba saber el siguiente turno?",
  "Appearance": "Apariencia",
  "Approve": "Aprobar",
  "Approved": "Aprobada",
  "Arrival": "Llegada",
  "Arriving": "Llegan",
  "Arriving today": "Llegan hoy",
  "Ask for time off or swap a shift with a colleague. Your manager approves it.": "Pide días libres o cambia un turno con un compañero. Tu encargado lo aprueba.",
  "Ask your marina manager to reset it. They manage staff accounts in the Marina web app.": "Pide a tu encargado de la marina que la restablezca. Gestiona las cuentas del personal en la web de Marina.",
  "Asked when you open the app or come back after a minute.": "Se pide al abrir la app o al volver después de un minuto.",
  "Assign to": "Asignar a",
  "At least 8 characters.": "Al menos 8 caracteres.",
  "Automatic": "Automático",
  "Available": "Libre",
  "Available in the phone app.": "Disponible en la app del teléfono.",
  "Berth": "Amarre",
  "Berth ready": "Amarre listo",
  "Berths": "Amarres",
  "Boat": "Embarcación",
  "Boat condition on arrival": "Estado de la embarcación al llegar",
  "Boat here now": "Embarcación aquí ahora",
  "Boat name": "Nombre de la embarcación",
  "Boat name, registration or owner": "Nombre, matrícula o propietario",
  "Boat owner": "Propietario",
  "Boat, owner, berth or code": "Embarcación, propietario, amarre o código",
  "Bookings": "Reservas",
  "Call": "Llamar",
  "Cancel": "Cancelar",
  "Cancelled": "Cancelada",
  "Change password": "Cambiar contraseña",
  "Charge": "Cargo",
  "Check in": "Registrar llegada",
  "Check out": "Registrar salida",
  "Checked in": "En la marina",
  "Choose marina": "Elegir marina",
  "Clock in": "Fichar entrada",
  "Clock out": "Fichar salida",
  "Clocked out. Any notes?": "Salida fichada. ¿Alguna nota?",
  "Close": "Cerrar",
  "Completed": "Terminada",
  "Confirm new password": "Confirma la nueva contraseña",
  "Confirmed": "Confirmada",
  "Confirms the boat's condition and the marina rules.": "Confirma el estado de la embarcación y las normas de la marina.",
  "Cover": "Cubrir",
  "Current password": "Contraseña actual",
  "Dark": "Oscuro",
  "Dates": "Fechas",
  "Day off today": "Hoy libras",
  "Decline": "Rechazar",
  "Declined": "Rechazada",
  "Demo": "Demo",
  "Dock map": "Mapa del muelle",
  "Dock patrol": "Ronda de muelles",
  "Done": "Hechas",
  "Due": "Vence",
  "Edit profile": "Editar perfil",
  "Email": "Correo",
  "Enter your email and password.": "Escribe tu correo y contraseña.",
  "Every open job has someone on it": "Todos los trabajos abiertos tienen responsable",
  "Facility": "Instalaciones",
  "First day off": "Primer día libre",
  "Forgot password?": "¿Olvidaste la contraseña?",
  "From the last shift": "Del turno anterior",
  "Full balance": "Saldo completo",
  "Good afternoon": "Buenas tardes",
  "Good evening": "Buenas noches",
  "Good morning": "Buenos días",
  "Guests": "Personas",
  "Half": "La mitad",
  "Has photos": "Tiene fotos",
  "How many days?": "¿Cuántos días?",
  "How urgent?": "¿Qué tan urgente?",
  "In": "Dentro",
  "In marina": "En la marina",
  "In progress": "En curso",
  "Issue": "Problema",
  "It goes straight to the marina's work orders.": "Va directo a las órdenes de trabajo de la marina.",
  "Leave": "Permiso",
  "Leave a note": "Dejar una nota",
  "Leaving": "Salen",
  "Leaving today": "Salen hoy",
  "Length (ft)": "Eslora (pies)",
  "Light": "Claro",
  "Low": "Baja",
  "Maintenance": "Mantenimiento",
  "Manager": "Encargado",
  "Marina manager": "Encargado de marina",
  "Mark as done": "Marcar como hecha",
  "Me": "Yo",
  "Medium": "Media",
  "Message": "Mensaje",
  "Messages": "Mensajes",
  "Messages, work orders and schedule changes show up here.": "Aquí aparecen mensajes, órdenes de trabajo y cambios de horario.",
  "Mine": "Mías",
  "My tasks": "Mis tareas",
  "My week": "Mi semana",
  "New booking": "Nueva reserva",
  "New password": "Nueva contraseña",
  "New request": "Nueva solicitud",
  "New total": "Nuevo total",
  "Next arrival": "Próxima llegada",
  "Nights": "Noches",
  "No arrivals today": "Hoy no llega nadie",
  "No berths with this status": "Ningún amarre con este estado",
  "No departures left today": "No quedan salidas hoy",
  "No hand-over notes in the last 24 hours.": "No hay notas de relevo en las últimas 24 horas.",
  "No messages yet": "Aún no hay mensajes",
  "No open work orders": "No hay órdenes abiertas",
  "No shift schedule linked to your account.": "Tu cuenta no tiene horario de turnos.",
  "Not clocked in": "Sin fichar",
  "Note": "Nota",
  "Nothing assigned to you": "No tienes nada asignado",
  "Nothing finished yet": "Aún no hay nada terminado",
  "Nothing here": "No hay nada aquí",
  "Nothing new": "Nada nuevo",
  "Notifications": "Avisos",
  "OK": "Bien",
  "Occupied": "Ocupado",
  "Off": "Libre",
  "Open": "Abiertas",
  "Open repairs": "Reparaciones abiertas",
  "Open tasks you start are assigned to you.": "Las tareas que empiezas se te asignan a ti.",
  "Open the web app": "Abrir la web",
  "Or type the berth number": "O escribe el número de amarre",
  "Overdue": "Atrasada",
  "Owner's name": "Nombre del propietario",
  "Paid": "Pagada",
  "Paid by": "Forma de pago",
  "Password": "Contraseña",
  "Past departure date": "Pasada la fecha de salida",
  "Pending": "Pendiente",
  "Phone": "Teléfono",
  "Point the camera at the QR label on the berth post": "Apunta la cámara al código QR del poste del amarre",
  "Price": "Precio",
  "Priority": "Prioridad",
  "Ready": "Listo",
  "Reason": "Motivo",
  "Recent rounds": "Rondas recientes",
  "Reminders on for your next 2 weeks of shifts": "Avisos activados para tus turnos de las próximas 2 semanas",
  "Repair": "Reparación",
  "Report": "Reportar",
  "Report a problem": "Reportar un problema",
  "Report as repair": "Reportar como reparación",
  "Request": "Solicitar",
  "Request withdrawn": "Solicitud retirada",
  "Reserved": "Reservado",
  "Run your marinas, berths and team from your phone.": "Gestiona tus marinas, amarres y equipo desde el teléfono.",
  "Save": "Guardar",
  "Save note": "Guardar nota",
  "Scan a berth label": "Escanear un código de amarre",
  "Scan berth": "Escanear amarre",
  "Scan berth QR code": "Escanear código QR del amarre",
  "Security": "Seguridad",
  "Send report": "Enviar reporte",
  "Send request": "Enviar solicitud",
  "Service": "Servicio",
  "Set up Face ID or a fingerprint on this phone first. Not available in the web preview.": "Configura primero Face ID o una huella en este teléfono. No disponible en la vista web.",
  "Shift reminders": "Avisos de turno",
  "Shift reminders off": "Avisos de turno desactivados",
  "Shift to swap": "Turno a cambiar",
  "Shown on the Today screen for the next 24 hours.": "Se muestra en la pantalla Hoy durante 24 horas.",
  "Sign in": "Iniciar sesión",
  "Sign out": "Cerrar sesión",
  "Signing in…": "Entrando…",
  "Skip": "Omitir",
  "Something's wrong: report it": "Algo está mal: repórtalo",
  "Staff": "Personal",
  "Start patrol": "Empezar ronda",
  "Start work": "Empezar trabajo",
  "Swap": "Cambio",
  "Take payment": "Cobrar",
  "Tasks": "Tareas",
  "They see it under Mine in their app.": "Lo verán en Mías en su app.",
  "Time off and swaps": "Días libres y cambios",
  "Timesheet": "Fichajes",
  "Today": "Hoy",
  "Try a boat name, owner or berth number.": "Prueba con un nombre, propietario o número de amarre.",
  "Turn on notifications for Marina in your phone's Settings.": "Activa los avisos de Marina en los Ajustes del teléfono.",
  "Type": "Tipo",
  "Unassigned": "Sin asignar",
  "Upcoming": "Próximas",
  "Urgent": "Urgente",
  "Urgent repairs": "Reparaciones urgentes",
  "Waiting": "En espera",
  "What did you see?": "¿Qué viste?",
  "What's wrong?": "¿Qué pasa?",
  "Who will cover?": "¿Quién cubrirá?",
  "Withdraw": "Retirar",
  "Work email": "Correo del trabajo",
  "You're offline. Keep working: changes are saved on this phone.": "Sin conexión. Sigue trabajando: los cambios se guardan en este teléfono.",
  "You're on leave today": "Hoy estás de permiso",
  "Your week is on the Me tab.": "Tu semana está en la pestaña Yo.",
  "days off": "días libres",
  "e.g. A-04": "p. ej. A-04",
  "e.g. Boat on B-03 leaves early tomorrow. Pump-out is low on fuel.": "p. ej. La embarcación del B-03 sale temprano mañana. La bomba de vaciado tiene poco combustible.",
  "e.g. Life ring missing at the end of Dock B": "p. ej. Falta un salvavidas al final del muelle B",
  "e.g. Power pedestal sparks when plugged in": "p. ej. El poste de luz echa chispas al enchufar",
  "e.g. Scratch on the port bow, about 30 cm": "p. ej. Rayón en la proa a babor, unos 30 cm",
  "guests": "personas",
  "nights": "noches",
  "you@company.com": "tu@empresa.com",
  "Language": "Idioma",
  "Report an incident": "Reportar un incidente",
  "Damage, injuries, theft or spills": "Daños, lesiones, robos o derrames",
  "What happened?": "¿Qué pasó?",
  "Damage": "Daños",
  "Injury": "Lesión",
  "Theft": "Robo",
  "Fuel or oil spill": "Derrame de combustible o aceite",
  "Other": "Otro",
  "Serious": "Grave",
  "Someone needed medical help, police were called, or there's ongoing danger. Call your manager too.": "Alguien necesitó atención médica, se llamó a la policía o sigue habiendo peligro. Llama también a tu encargado.",
  "Where (optional)": "Dónde (opcional)",
  "Not at a berth": "No es en un amarre",
  "Describe what happened": "Describe lo que pasó",
  "Describe what happened.": "Describe lo que pasó.",
  "e.g. Visiting boat hit the end of B dock while docking. Two boards cracked, nobody hurt.": "p. ej. Una embarcación visitante golpeó el final del muelle B al atracar. Dos tablas rotas, nadie herido.",
  "People involved or witnesses (optional)": "Personas implicadas o testigos (opcional)",
  "Incident reported. Your manager has been told.": "Incidente reportado. Tu encargado ya lo sabe.",
  "Parts used": "Repuestos usados",
  "None yet.": "Ninguno todavía.",
  "left": "quedan",
  "Use part": "Usar repuesto",
  "Last week": "Semana pasada",
  "Approved by {name}": "Aprobado por {name}",
  "Waiting for approval": "Pendiente de aprobación",
  "task|Open": "Abierta",
  "task|Done": "Hecha",
  "Work orders": "Órdenes de trabajo",
  "Berth {code}": "Amarre {code}",
  "due {when}": "vence {when}",
  "{shift} shift": "Turno de {shift}",
  "Morning": "mañana",
  "Day": "día",
  "Evening": "tarde",
  "Night": "noche",
  "Patrol in progress": "Ronda en curso",
  "{n} checked so far. Tap to continue.": "{n} revisados hasta ahora. Toca para seguir.",
  "Walk the docks and safety checks.": "Recorre los muelles y las revisiones de seguridad.",
  "On the clock since {time}": "Fichado desde las {time}",
};
